apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-app.yaml  # Reference đến file deployment

# Common labels cho tất cả resources
commonLabels:
  app: thesis-simple
  managed-by: argocd