apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
- ../../applications/thesis-simple/base/

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: thesis-simple-uat
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: nginx:1.23-alpine  # UAT: version ổn định để test
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: thesis-simple