apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment }}-thesis-simple
  labels:
    app: thesis-simple
    environment: {{ .Values.environment }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: thesis-simple
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: thesis-simple
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
