apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-thesis-simple
  labels:
    app: thesis-simple
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: thesis-simple
    environment: {{ .Values.environment }}
