apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../applications/thesis-simple/base/

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: thesis-simple-dev
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: nginx:latest  # DEV: dùng latest để test nhanh
  target:
    kind: Deployment
    name: thesis-simple